apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tokn

labels:
- pairs:
    app: tokn-website

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image-updater.yml
  - pdb.yaml
