name: PR Check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.13.0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run types:check

      - name: Test Build
        run: pnpm run build
